test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,6 +34,21 @@ jobs:
       - name: Start containers
         run: docker compose --profile test up -d
 
+      - name: Get Check Run Logs
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ github.token }}
+          script: |
+            const checkRunId = '37794310970';  // Replace with your check run ID
+            const response = await github.rest.checks.get({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              check_run_id: checkRunId
+            });
+            const logsUrl = response.data.output.annotations_url;
+            info(`Check Run Logs URL: ${logsUrl}`);
+              
+            return response.data.output;
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
@@ -44,6 +59,36 @@ jobs:
         uses: gradle/actions/setup-gradle@v4
         with:
           cache-read-only: ${{ github.ref != 'refs/heads/main' }}
+
+      - name: Generate a token
+        id: generate-app-token
+        continue-on-error: true
+        uses: actions/create-github-app-token@v1.9.3
+        with:
+          app-id: ${{ secrets.GH_APP_ID }}
+          private-key: ${{ secrets.JAVA_BACKEND_APP_PRIVATE_KEY }}
+          owner: ${{ github.repository_owner }}
+
+      - name: Fetch PR Labels
+        id: fetch-labels
+        shell: 'bash'
+        run: |
+          LABELS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq '.labels[].name' || echo "")
+          LABELS_CLEAN=$(echo "$LABELS" | tr '\n' ',' | sed 's/,$//')
+          echo "labels=$LABELS_CLEAN" >> $GITHUB_ENV
+        env:
+          GH_TOKEN: ${{ inputs.github-token }}
+
+      - name: Check for Suppress Label
+        id: check-label
+        shell: 'bash'
+        run: |
+          if echo "$labels" | grep -q 'suppress-delta-coverage'; then
+          echo "suppress_check_failures=true" >> $GITHUB_ENV
+          else
+          echo "suppress_check_failures=false" >> $GITHUB_ENV
+          fi        
+      
 
       - name: Run gradle build
         run: ${gradle_cmd} build
@@ -62,5 +107,5 @@ jobs:
       - name: Append Coverage Summary
         if: ${{ !cancelled() }}
         continue-on-error: true
-        uses: ajax-yurkovskyi-t/delta-coverage-action@feature/dynamic-label-fetching
+        uses:  ajax-yurkovskyi-t/delta-coverage-action@feature/dynamic-label-fetching
 
